export const authTypes = {
  SIGNUP_START: "SIGNUP_START",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAIL: "SIGNUP_FAIL",
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAIL: "SIGN_IN_FAIL",
  SET_USER_PERMISSIONS: "SET_USER_PERMISSIONS",
  CLEAR_ERROR_MESSAGE: "CLEAR_ERROR_MESSAGE",
  SIGNOUT: "SIGNOUT",
};
